import type { NextPage } from 'next';
import Head from 'next/head';
import { ConnectKitButton } from 'connectkit';
import { useWalletContext } from '@/app/wallet';
import { useDisconnect } from 'wagmi';

const Home: NextPage = () => {
  const { address, status, Disconnect } = useWalletContext();

  return (
    <div className="font-inter">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex flex-col items-center gap-4 py-8">
          <div className="flex items-center gap-4">
            <ConnectKitButton />
            <ConnectKitButton.Custom>
              {({
                isConnected,
                isConnecting,
                show,
                hide,
                address,
                ensName,
                truncatedAddress,
              }) => {
                return (
                  <button
                    onClick={show}
                    className="py-2 px-6 bg-green-500 text-white rounded-lg hover:bg-green-600 active:scale-95"
                  >
                    {isConnected ? truncatedAddress : 'Custom Connect'}
                  </button>
                );
              }}
            </ConnectKitButton.Custom>
            {address && (
              <button
                onClick={() => Disconnect()}
                className="py-2 px-6 bg-green-500 text-white rounded-lg hover:bg-green-600 active:scale-95"
              >
                Disconnect
              </button>
            )}
          </div>

          <div className="text-center">
            <div>Status:</div>
            <div className="text-red-500">{status}</div>
            {address && <div>{address}</div>}
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
