import type { NextPage } from 'next';
import { useAlert } from 'react-alert';
import Head from 'next/head';
import { ConnectKitButton } from 'connectkit';
import { useAccount } from 'wagmi';

const Home: NextPage = () => {
  const alert = useAlert();
  const { address, status } = useAccount();

  return (
    <div className="font-inter">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ConnectKitButton />

        <div>Status:</div>
        <div className="text-red-500">{status}</div>
        {address && <div>Connected Wallet: {address}</div>}

        {/* <button
          onClick={() => {
            alert.success('Yeyyy!');
            alert.error('Yeyyy!');
            alert.info('Yeyyy!');
          }}
        >
          Alert
        </button> */}
      </main>
    </div>
  );
};

export default Home;
