import { useGlobalState } from '@/app/store';
import { useWalletContext } from '@/app/wallet';
import { useHookstate } from '@hookstate/core';
import { ConnectKitButton } from 'connectkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';

const Home: NextPage = () => {
  const gState = useGlobalState();
  const { alert, status, address, Disconnect, isDisconnected, ctxContract } =
    useWalletContext();
  const balance = useHookstate(0);
  const recipient = useHookstate('');
  const amount = useHookstate(0);

  const getBusdBal = async () => {
    const data = await ctxContract.busd.balanceOf(
      gState['wallet']['address'].value ||
        '0x07E2403ad511FA85A388AeB300d47657D2ae292d'
    );

    const bal = await toBUSD(data.toString());
    balance.set(bal);
    alert.success(`Balance: ${bal}`);
  };

  const sendBusd = async () => {
    try {
      const _amount = await toRawBUSD(amount.value);
      const data = await ctxContract.busd.transfer(recipient.value, _amount);

      console.log('TEST: ', data);
      alert.success('SENT SUCCESS');
    } catch (error) {
      alert.error(error.message);
    } finally {
      getBusdBal();
    }
  };

  const toBUSD = async (price) => {
    const usdtDecimal = await ctxContract.busd.decimals();
    return Number(price) / 10 ** Number(usdtDecimal);
  };

  const toRawBUSD = async (price) => {
    const usdtDecimal = await ctxContract.busd.decimals();
    return Number(price) * 10 ** Number(usdtDecimal);
  };

  useEffect(() => {
    if (isDisconnected) {
      balance.set(0);
    }
  }, [isDisconnected]);

  return (
    <div className="font-inter">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white min-h-screen">
        <div className="flex flex-col items-center gap-4 py-8">
          <div className="flex items-center gap-4">
            <ConnectKitButton />
            <ConnectKitButton.Custom>
              {({ show, isConnected, truncatedAddress }) => {
                return (
                  <button
                    onClick={show}
                    className="py-2 px-6 bg-green-500 text-white rounded-lg hover:bg-green-600 active:scale-95"
                  >
                    {isConnected ? truncatedAddress : 'Custom Connect'}
                  </button>
                );
              }}
            </ConnectKitButton.Custom>
            {address && (
              <button
                onClick={() => Disconnect()}
                className="py-2 px-6 bg-red-500 text-white rounded-lg hover:bg-red-600 active:scale-95"
              >
                Disconnect
              </button>
            )}
          </div>

          <div className="text-center">
            <div>Status:</div>
            <div className="text-red-500">{status}</div>
            {address && <div>{address}</div>}
          </div>

          <div className="flex flex-col items-center">
            <button
              onClick={getBusdBal}
              className="py-2 px-6 bg-green-500 text-white rounded-lg hover:bg-green-600 active:scale-95"
            >
              GET BUSD BALANCE
            </button>
            <div>{`BUSD Balance: ${balance.value.toLocaleString()}`}</div>
          </div>

          {address && (
            <div className="space-y-8 pt-6">
              <div className="flex flex-col items-center gap-2">
                <input
                  className="border px-4 py-1"
                  type="text"
                  value={recipient.value}
                  onChange={(e) => recipient.set(e.target.value)}
                  placeholder="Recipient Address"
                />
                <input
                  className="border px-4 py-1"
                  type="number"
                  value={amount.value}
                  onChange={(e) => amount.set(Number(e.target.value))}
                  placeholder="Amount"
                />
                <button
                  onClick={sendBusd}
                  className="py-2 px-6 bg-green-500 text-white rounded-lg hover:bg-green-600 active:scale-95"
                >
                  SEND
                </button>
              </div>
            </div>
          )}
        </div>
      </main>
    </div>
  );
};

export default Home;
